# -*- coding: utf-8 -*-
"""Simple IIoT Sensor Network Simulation_jabarr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTP00t341yS9DTLqR-rNa822EQ73vhmb
"""

!pip install paho-mqtt pandas numpy matplotlib

import random
import time
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

# Simulate sensor data directly
def simulate_sensor_data():
    # Initialize cumulative data list
    sensor_data = []

    # Simulate 50 data points
    for i in range(50):
        temp = random.uniform(20.0, 25.0)
        hum = random.uniform(30.0, 50.0)
        timestamp = datetime.now()
        sensor_data.append((timestamp, temp, hum))
        print(f"Iteration {i+1}: Temp={temp:.1f}°C, Hum={hum:.1f}%")  # Debug print

        time.sleep(1)  # Simulate real-time data collection

    # Create DataFrame from all data
    df = pd.DataFrame(sensor_data, columns=["timestamp", "temperature", "humidity"])

    # Create a static plot
    plt.figure(figsize=(10, 6))
    plt.plot(df["timestamp"], df["temperature"], label="Temperature (°C)", color="red")
    plt.plot(df["timestamp"], df["humidity"], label="Humidity (%)", color="blue")
    plt.xlabel("Time")
    plt.ylabel("Value")
    plt.ylim(15, 55)  # Cover temperature and humidity range
    plt.legend()
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.title("IIoT Sensor Simulation: Temperature and Humidity")
    plt.tight_layout()

    # Save and display the plot
    plt.savefig("mqtt_visualization.png")
    plt.show()

simulate_sensor_data()

# IIoT Sensor Network Simulation
Simulates an IIoT sensor network in Google Colab.
- `mqtt_sensor_simulation.py`: Simulates temperature/humidity data and visualizes it.
- Requires `pandas`, `numpy`, `matplotlib`.
- Results in `visualizations/mqtt_visualization.png`.
- Note: Simplified without MQTT due to Colab limitations.